#### introduction
Zipkin是一个分布式链路跟踪系统，可以采集时序数据来协助定位延迟等相关问题。数据可以存储在cassandra,MySQL,ES,mem中
\\ https://zipkin.io/pages/architecture.html


####architecture

instrumention --------> transport------>collector------->storage
-         -                                           -     -
-         -                                          -      -
-         -                                        -        -
span   repoter                                 WEBUI      search



####prepare
##prepare images
es      \\ zipkin db storage
zipkin  \\ api link tracking

docker pull openzipkin/zipkin
dpcker pull elasticsearch:7.6.2

##prepare start es server by docker


mkdir -p 777 /data/elasticsearch
chmod -R 777 /data/elasticsearch

vi elasticsearch.yml

cluster.name: "docker-cluster"
network.host: 0.0.0.0
xpack.security.enabled: true


docker run -d \
    --user root \
    -p 192.168.0.121:9200:9200 \
    -p 9300:9300 \
    --log-driver json-file \
    --log-opt max-size=10m \
    --log-opt max-file=3 \
    --name elasticsearch \
    --restart=always \
    -e "discovery.type=single-node" \
    -v /data/elasticsearch:/usr/share/elasticsearch/data \
   -v /root/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml \
    elasticsearch:7.6.2

#set es pass
docker exec -it elasticsearch /bin/bash
cd bin
elasticsearch-setup-passwords interactive
elastic
123456

docker restart elasticsearch


##prepare k8s yml
\\ https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
\\ https://github.com/openzipkin-attic/docker-zipkin


#zipkin.yml

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: zipkin
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      k8s-app: zipkin
  template:
    metadata:
      labels:
        k8s-app: zipkin
    spec:
      containers:
      - name: zipkin
        imagePullPolicy: IfNotPresent
        image: 192.168.0.121:5000/basic/zipkin
        securityContext:
          capabilities:
            add: ["SYS_PTRACE"]
        env:
        - name: release_environment
          value: "live"
        - name: STORAGE_TYPE
          value: "elasticsearch"
        - name: ES_HOSTS
          value: "192.168.0.121"
        - name: ES_USERNAME
          value: "elastic"
        - name: ES_PASSWORD
          value: "123456"
        ports:
          - containerPort: 9411
            name: zipkin
            protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 1Gi
      imagePullSecrets:
        - name: harborsecretname

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: zipkin
  labels:
    k8s-app: zipkin
spec:
  type: NodePort
  ports:
    - port: 9411
      targetPort: 9411
      protocol: TCP
  selector:
    k8s-app: zipkin


####zipkin test
\\ python test
pip install py-zipkin
pip install pyramid
pip install pyramid-zipkin

git clone https://github.com/openzipkin/pyramid_zipkin-example.git
cd pyramid_zipkin-example
vi transport.py
        requests.post(
        #'http://localhost:9411//api/v2/spans',
        'http://192.168.0.118:30235//api/v2/spans',

python setup.py install


nohup python backend.py &
http://localhost:9000/api

nohup python frontend.py &
visit http://localhost:8081/


############### docker depoly

## doc 
https://zipkin.io/pages/quickstart.html
https://github.com/openzipkin-attic/docker-zipkin/blob/master/docker-compose.yml

## arch
repoter -------> transport (http)-------> zipkin -------> db(es)
## images
docker pull openzipkin/zipkin
docker pull docker.elastic.co/elasticsearch/elasticsearch:7.9.2
docker pull docker.elastic.co/kibana/kibana:7.9.2

## net prepare
docker network create --subnet=172.18.2.0/24 docker-ice

## es prepare

mkdir -p 777 /data/elasticsearch/data
chmod -R 777 /data/elasticsearch/data
mkdir -p 777 /data/docker/kibana/{plugin,data}
chmod -R 777 /data/docker/kibana

vi /data/elasticsearch/elasticsearch.yml

cluster.name: "docker-cluster"
network.host: 0.0.0.0
xpack.security.enabled: true


docker run -d \
    --user root \
    -p 9200:9200 \
    -p 9300:9300 \
    -m 2048m \
    --cpus 2 \
    --net docker-ice \
    --ip 172.18.2.2 \
    --log-driver json-file \
    --log-opt max-size=10m \
    --log-opt max-file=3 \
    --name zipkin-es \
    --restart=always \
    -e "discovery.type=single-node" \
    -v /data/elasticsearch/data:/usr/share/elasticsearch/data \
    -v /data/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml \
    docker.elastic.co/elasticsearch/elasticsearch:7.9.2

#set es pass
docker exec -it zipkin-es /bin/bash
cd bin
elasticsearch-setup-passwords interactive
elastic
Muyed4gq2RE7wgNQ

docker restart zipkin-es


## start zipkin

docker run -d \
    --user root \
    -p 9411:9411 \
    -m 2048m \
    --cpus 2 \
    --net docker-ice \
    --ip 172.18.2.3 \
    --name zipkin \
    --restart=always \
    -e "STORAGE_TYPE=elasticsearch" \
    -e "ES_HOSTS=172.18.2.2" \
    -e "ES_USERNAME=elastic" \
    -e "ES_PASSWORD=Muyed4gq2RE7wgNQ" \
    openzipkin/zipkin


## client test

https://zipkin.io/pages/tracers_instrumentation.html


## zipkin 使用规范

   serviceName: 使用 zipkin 的客户端名； 接口名 api_rule: /api/[sfa-content]/[sub_function]/[get|put|update...]
   spanName: 完成整个请求中的单个处理单元
   
## zipkin es index 管理: 数据备份时长: index 按天索引，可定期清理
## zipkin monitor https://zipkin.io/zipkin-api/#/default/post_spans
curl -X GET "http://localhost:9411/api/v2/services" -H  "accept: application/json"
# check status code
import requests
"""
https://zipkin.io/zipkin-api/#/default/get_services

"""

url = "http://47.245.53.23:9411/api/v2/services"

payload = {}
headers = {
  'Content-Type': 'application/json'
}

response = requests.request("GET", url, headers=headers, data=payload).status_code
print(response)
# print(response.text.encode('utf8'))

## zipkin 结合 grafana 数据可视化 统计调用 api 的 error_code 数量


## kibana

docker run -d \
    -p 0.0.0.0:5601:5601 \
    --log-driver json-file \
    --log-opt max-size=10m \
    --log-opt max-file=3 \
    --name kibana \
    --restart=always \
    --net docker-ice \
    -e "max-old-space-size=1024" \
    -e "SERVER_NAME=kibana" \
    -e "ELASTICSEARCH_HOSTS=http://172.18.2.2:9200" \
    -e "SERVER_HOST=0.0.0.0" \
    -e "ELASTICSEARCH_USERNAME=kibana" \
    -e "ELASTICSEARCH_PASSWORD=Muyed4gq2RE7wgNQ" \
    -e "xpack.security.encryptionKey=something_at_least_32_characters" \
    -v /data/docker/kibana/plugin:/usr/share/kibana/plugins/ \
    -v /data/docker/kibana/data:/usr/share/kibana/data/ \
    -v /etc/localtime:/etc/localtime:ro \
    -m 3048m \
    --cpus 2 \
    docker.elastic.co/kibana/kibana:7.9.2
